<a href="https://colab.research.google.com/github/AbiXnash/Machine-Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Numpy** ->` Faster Arithmetic Operations`
---
- Numpy is like the Swiss Army knife of numerical computing in Python.
- It provides a powerful array object, essential for scientific computing, and a collection of functions to operate on these arrays.
- This makes it efficient and convenient for tasks like linear algebra, statistical analysis, and other mathematical operations.
- Plus, it's widely used in the data science and machine learning communities, so it's a handy tool to have in your programming arsenal.
---
**For More Details**: [NumPy.org](https://numpy.org/)






### **Import**

In [ ]:
import numpy as np

---

### **Declaration**

- Elements should be passed as **list**
- For 2D array, elements are passed as **list of tuples**

In [ ]:
np_array = np.array([])

---

### **List vs. NumPy**

In [ ]:
# Module to calculate time
from time import process_time

---

#### List

In [ ]:
''' Python's List Test '''

# Creating list
list = [i for i in range(10000000)]

start_time = process_time() # Start time
list = [i + 5 for i in list] # Adding 5 to each element
end_time = process_time() # End time

print(end_time - start_time) # Calculating time difference

0.8129885450000032


---

#### NumPy array

In [ ]:
''' Numpy's Array Test '''

# Creating Numpy Array
array = np.array([i for i in range(10000000)])

start_time = process_time() # Start time
array += 5 # Adding 5 to each element
end_time = process_time() # End time

print(end_time - start_time) # Calculating time difference

0.010682343000002703


---

*It's clear that Numpy is faster*

### **Numpy Data Type**

*NumPy arrays have a fixed data type for their elements*

In [ ]:
''' Numpy Data Type '''
print(type(array))

<class 'numpy.ndarray'>


---

### **Dimensions of Array**

In [ ]:
''' Intialization one dimensional array '''
array_1d = np.array([1, 2, 3, 4, 5]) # Parameter -> list
print(array_1d)

[1 2 3 4 5]


In [ ]:
''' Intialization two dimensional array '''
array_2d = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)]) # Parameter -> list of tuples
print(array_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


---

#### **Shape Attribute** -> `shape`

*returns `(rows, columns)`*

In [ ]:
array_1d.shape # in 1D array, all elements are *rows*

(5,)

In [ ]:
array_2d.shape # in 2D array, each tuples are *rows*

(2, 5)

---

### **Changing Data Type** -> `dtype`

It changes the **data type of the element** not the array

In [ ]:
''' np.array(elements, dtype = {data type}) '''
array = np.array([(1, 2, 3), (4, 5, 6)], dtype = float)
print(array, type(array))

[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.ndarray'>


---

### **Placeholders**

`dtype` parameter in optional.

#### Array of Zeros

In [ ]:
''' np.zeros((rows, columns), dtype = {data type}) '''
array = np.zeros((4, 5), dtype = int) # pass as tuples of rows and columns
print(array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


---

#### Array of Ones

In [ ]:
''' np.ones((rows, columns), dtype = {data type}) '''
array = np.ones((4, 5), dtype = int) # pass as tuples of rows and columns
print(array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


---

#### Array of any numbers

In [ ]:
''' np.ones((rows, columns), {number}) '''
array = np.full((4, 5), 5, dtype = float) # pass the number along with tuples of rows and columns
print(array)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


---

#### Identity Matrix

In [ ]:
''' np.eye({number}, dtype = {data type}) '''
array = np.eye(5, dtype = int) # number of rows and columns are same so pass it as single number
print(array)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


---

#### Array of random numbers

In `random()`, random numbers are generated between **0.00000000** to **0.99999999**

In [ ]:
''' np.random.random (({rows}, {columns})) '''
array = np.random.random((4, 5))
print(array)

[[0.86543855 0.53140504 0.3619396  0.25931785 0.36857773]
 [0.11986376 0.37401957 0.94830572 0.8158487  0.50811578]
 [0.95592875 0.9040678  0.06534931 0.03766765 0.056259  ]
 [0.56389432 0.99398396 0.37010883 0.10180956 0.65934371]]


In `randint()`, random numbers are generated between the **given range**.

In [ ]:
''' np.random.random ({starting_number}, {ending_number} ({rows}, {columns})) '''
array = np.random.randint(1, 100, (4, 5)) # ending_number in exclusive
print(array)

[[76 63 64 31 17]
 [28  7 21 15 46]
 [34 27 56 60 66]
 [86 71 76 81 58]]


---

#### Other Numpy Methods  

**`linspace()`** Method

In [ ]:
''' np.linspace ({starting_number}, {ending_number}, {number_of_elements}, dtype = {data type}) '''
array = np.linspace(1, 100, 10, dtype = int)
print(array)

[  1  12  23  34  45  56  67  78  89 100]


**`arange()`** Method

In [ ]:
''' np.arange ({starting_number}, {ending_number}, {steps}, dtype = {data type}) '''
array = np.arange(1, 100, 10, dtype = int)
print(array)

[ 1 11 21 31 41 51 61 71 81 91]


---

### **List to Numpy Convertion**

---